name:                duckbot
version:             0.1.0.0
github:              "DuckOfDoom/duckbot"
license:             BSD3
author:              "DuckOfDoom"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/duckbot#readme>

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- protolude
- mtl
- transformers
- aeson
- aeson-pretty
- wreq
- neat-interpolation
- text
- bytestring
- lens
- time
- unordered-containers
- wai
- wai-extra
- http-types
- warp

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- LambdaCase

library:
  source-dirs: src

executables:
  duckbot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - duckbot

tests:
  duckbot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - duckbot
